package org.wsssoapbox.database.logger;
// Generated Feb 6, 2012 5:24:14 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserLog generated by hbm2java
 */
public class UserLog  implements java.io.Serializable {
   private static final long serialVersionUID = 813012870838964634L;

     private Integer logId;
     private Date date;
     private String logger;
     private String level;
     private String message;
     private int userId;

    public UserLog() {
    }

    public UserLog(Date date, String logger, String level, String message, int userId) {
       this.date = date;
       this.logger = logger;
       this.level = level;
       this.message = message;
       this.userId = userId;
    }
   
    public Integer getLogId() {
        return this.logId;
    }
    
    public void setLogId(Integer logId) {
        this.logId = logId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getLogger() {
        return this.logger;
    }
    
    public void setLogger(String logger) {
        this.logger = logger;
    }
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }




}


